# Generated by Django 2.2.7 on 2019-11-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'sexo',
                'verbose_name_plural': 'sexos',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.CharField(max_length=30, unique=True, verbose_name='documento de identidad')),
                ('first_name', models.CharField(max_length=60, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=60, verbose_name='apellidos')),
                ('birth_date', models.DateField(verbose_name='fecha de nacimiento')),
                ('monthly_salary', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='salario mensual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.Sex', verbose_name='sexo')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
            },
        ),
    ]
